### ISSUE TITLE
Revise metadata for selected vars

### ISSUE THREAD

**Issue by yzhang104** [sleepepi/hchs-data-dictionary#17]
1. move to signal quality folder:
slpa12 
slpa13 – Total valid SpO2 recording period in supine position from type IV home sleep apnea test
slpa14 – Total valid SpO2 recording period in non-supine position from type IV home sleep apnea test

2. drop the following variables: slpa105-slpa110

3. add the following tags to variables:
hchs_sleep_questionnaire to all slea* var
hchs_sleep_questionnaire_ancillary to all spea* var
hchs_sleep_questionnaire_2_ancillary to all sqea*var

4. remove slpa27, slpa29.

**Comment by mrueschman** [comment]
Completed in https://github.com/nsrr/hchs-data-dictionary/commit/e882a14bd0597fb8c4b75127368da6fc1b131813
