### ISSUE TITLE
Add Insomnia Severity Index (ISI) raw variables

### ISSUE THREAD

**Issue by yzhang104** [sleepepi/hchs-data-dictionary#8]

**Comment by mrueschman** [comment]
I assume you're also interested in the WHIIRS raw variables, right?

**Comment by yzhang104** [comment]
I think the raw whiirs variables are already uploaded, just not labeled - I assume they are slea4,5,6,7 and 11?

**Comment by mrueschman** [comment]
That is right, the SLEA variables are the WHIIRS variables for the HCHS Baseline visit. It looks like ISI is just from the Sueno Ancillary, and I noticed when looking this up that the raw variables for WHIIRS_SUENO were not included (they are from a dataset named SPEA).

**Comment by yzhang104** [comment]
I see. Yes, it would be helpful to get the whiirs variables from the ancillary study as well. thanks!

**Comment by mrueschman** [comment]
Will do!
